"""Add language column to projects

Revision ID: 464388f2fac5
Revises: 004_add_template_style
Create Date: 2026-01-01 13:42:44.651185

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '464388f2fac5'
down_revision = '004_add_template_style'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('projects', sa.Column('language', sa.String(length=10), nullable=False, server_default='en'))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('projects', 'language')
    # ### end Alembic commands ###



